name: Checks

on: push

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Load Function
        run: source custom/plugins/zhaoli/shellcheck.sh
      - name: Lint Application
        run: lint_project

