name: Checks

on: push

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Application
        run: shellcheck -- .bashrc .bash_profile *.sh scripts/tasks/*.sh custom/plugins/zhaoli/*.sh

