name: Ubuntu 16.04

on: push

jobs:
  bootstrap:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Bootstrap
        run: ./bootstrap.sh

