name: Ubuntu 18.04

on: push

jobs:
  bootstrap:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Bootstrap
        run: ./bootstrap.bash

